# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: private-pool
  vmImage: MBD5C4CV4WXL

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.X'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  displayName: "Install dependencies"
  inputs:
    script: |
      python3 -m pip install -r $(Build.SourcesDirectory)/requirements.txt
      python3 -m pip install -r $(Build.SourcesDirectory)/src/tests/tests-requirements.txt

- task: CmdLine@2
  displayName: "Run tests"
  inputs:
    script: |
      pytest $(Build.SourcesDirectory)

- task: CmdLine@2
  displayName: "Build"
  inputs:
    script: |
      docker build --tag metadata-demo $(Build.SourcesDirectory)
      docker ps




