# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: private-pool
  vmImage: MBD5C4CV4WXL

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.X'
    addToPath: true
    architecture: 'x64'
  
- task: PythonScript@0
  displayName: "Create virtual environment"
  inputs:
    scriptSource: 'inline'
    script: |
      -m venv $(Build.SourceDirectory)/venv/
      source $(Build.SourceDirectoy)/venv/bin/activate

- task: PythonScript@0
  displayName: "Install dependencies"
  inputs:
    scriptSource: 'inline'
    script: |
      -m pip install -r $(Build.SourcesDirectory)/requirements.txt
      -m pip install -r $(Build.SourcesDirectory)/src/test/test-requirements.txt

- task: CmdLine@2
  displayName: "Run tests"
  inputs:
    script: |
      pytest $(Build.SourcesDirectory)

- task: CmdLine@2
  displayName: "Run tests"
  inputs:
    script: |
      docker build --tag metadata-demo $(Build.SourcesDirectory)
      docker ps




